Repository FashionFreedom/Seamly2D, pull requests merged in 2020-09, with the labels that each got.

#304 Remove deprecated ChangeLog.txt
  ChangeLog.txt
Labels: repository

#309 Fix Curve & Axis Intersection point result
  src/app/seamly2d/core/vapplication.cpp
  src/app/seamly2d/mainwindow.cpp
  src/app/seamlyme/mapplication.cpp
  src/app/seamlyme/tmainwindow.cpp
  src/libs/vtools/dialogs/tools/piece/dialoginternalpath.cpp
  src/libs/vtools/dialogs/tools/piece/dialogseamallowance.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toollinepoint/vtoolcurveintersectaxis.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toollinepoint/vtoolcurveintersectaxis.h
  src/libs/vtools/visualization/line/operation/vistoolmove.cpp
  src/libs/vtools/visualization/line/operation/vistoolrotation.cpp
  src/libs/vtools/visualization/line/vistoolcurveintersectaxis.cpp
  src/libs/vtools/visualization/line/vistoolendline.cpp
  src/libs/vtools/visualization/line/vistoollineintersectaxis.cpp
  src/libs/vtools/visualization/path/vistoolcubicbezierpath.cpp
  src/libs/vtools/visualization/path/vistoolspline.cpp
  src/libs/vtools/visualization/path/vistoolsplinepath.cpp
Labels: Draw mode, bug

#316 fixed c++ encoding issue #315
  .gitattributes
Labels: build, repository

#318 issue #315, removed duplicates
  .gitattributes
Labels: build

#319 Add arc/segments in the "point intersection curves" tool issue-#317
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/vtoolpointofintersectioncurves.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/vtoolpointofintersectioncurves.h
Labels: Curve Tools, bug

#321 Build: Update debian to qt 5.9.5 (bionic) issue #320
  dist/debian/control
Labels: Linux, build
