Repository FashionFreedom/Seamly2D, pull requests merged in 2021-11, with the labels that each got.

#468 fix pragma message \n
  src/app/seamly2d/stable.h
  src/app/seamlyme/stable.h
  src/libs/fervor/stable.h
  src/libs/ifc/stable.h
  src/libs/qmuparser/stable.h
  src/libs/vdxf/stable.h
  src/libs/vformat/stable.h
  src/libs/vgeometry/stable.h
  src/libs/vlayout/stable.h
  src/libs/vmisc/stable.h
  src/libs/vobj/stable.h
  src/libs/vpatterndb/stable.h
  src/libs/vpropertyexplorer/stable.h
  src/libs/vtest/stable.h
  src/libs/vtools/stable.h
  src/libs/vwidgets/stable.h
  src/test/CollectionTest/stable.h
  src/test/ParserTest/stable.h
  src/test/Seamly2DTest/stable.h
  src/test/TranslationsTest/stable.h
Labels: build

#469 remove pragma messages
  src/app/seamly2d/stable.h
  src/app/seamlyme/stable.h
  src/libs/fervor/stable.h
  src/libs/ifc/stable.h
  src/libs/qmuparser/stable.h
  src/libs/vdxf/stable.h
  src/libs/vformat/stable.h
  src/libs/vgeometry/stable.h
  src/libs/vlayout/stable.h
  src/libs/vmisc/stable.h
  src/libs/vobj/stable.h
  src/libs/vpatterndb/stable.h
  src/libs/vpropertyexplorer/stable.h
  src/libs/vtest/stable.h
  src/libs/vtools/stable.h
  src/libs/vwidgets/stable.h
  src/test/CollectionTest/stable.h
  src/test/ParserTest/stable.h
  src/test/Seamly2DTest/stable.h
  src/test/TranslationsTest/stable.h
Labels: build

#501 Issue #132 different colors on cut lines
  src/app/seamly2d/dialogs/configpages/preferencesgraphicsviewpage.ui
  src/app/seamly2d/dialogs/configpages/preferencespatternpage.cpp
  src/app/seamly2d/dialogs/configpages/preferencespatternpage.ui
  src/app/seamly2d/xml/vpattern.cpp
  src/libs/ifc/ifcdef.cpp
  src/libs/ifc/ifcdef.h
  src/libs/vdxf/vdxfengine.cpp
  src/libs/vlayout/vgraphicsfillitem.cpp
  src/libs/vlayout/vgraphicsfillitem.h
  src/libs/vlayout/vlayoutpiece.cpp
  src/libs/vlayout/vlayoutpiece.h
  src/libs/vlayout/vlayoutpiece_p.h
  src/libs/vlayout/vposition.cpp
  src/libs/vmisc/vcommonsettings.cpp
  src/libs/vmisc/vcommonsettings.h
  src/libs/vpatterndb/vpiece.cpp
  src/libs/vtools/dialogs/tools/dialogalongline.cpp
  src/libs/vtools/dialogs/tools/dialogbisector.cpp
  src/libs/vtools/dialogs/tools/dialogcurveintersectaxis.cpp
  src/libs/vtools/dialogs/tools/dialogendline.cpp
  src/libs/vtools/dialogs/tools/dialogheight.cpp
  src/libs/vtools/dialogs/tools/dialogline.cpp
  src/libs/vtools/dialogs/tools/dialoglineintersectaxis.cpp
  src/libs/vtools/dialogs/tools/dialognormal.cpp
  src/libs/vtools/dialogs/tools/dialogshoulderpoint.cpp
  src/libs/vtools/dialogs/tools/piece/dialoginternalpath.cpp
  src/libs/vtools/tools/drawTools/toolcurve/vabstractspline.cpp
  src/libs/vtools/tools/drawTools/toolcurve/vtoolarc.cpp
  src/libs/vtools/tools/drawTools/toolcurve/vtoolarcwithlength.cpp
  src/libs/vtools/tools/drawTools/toolcurve/vtoolcubicbezier.cpp
  src/libs/vtools/tools/drawTools/toolcurve/vtoolcubicbezierpath.cpp
  src/libs/vtools/tools/drawTools/toolcurve/vtoolellipticalarc.cpp
  src/libs/vtools/tools/drawTools/toolcurve/vtoolspline.cpp
  src/libs/vtools/tools/drawTools/toolcurve/vtoolsplinepath.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toolcut/vtoolcutarc.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toolcut/vtoolcutspline.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toolcut/vtoolcutsplinepath.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toollinepoint/vtoolalongline.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toollinepoint/vtoolbisector.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toollinepoint/vtoolcurveintersectaxis.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toollinepoint/vtoolendline.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toollinepoint/vtoolheight.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toollinepoint/vtoollineintersectaxis.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toollinepoint/vtoollinepoint.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toollinepoint/vtoolnormal.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toollinepoint/vtoolshoulderpoint.cpp
  src/libs/vtools/tools/drawTools/vtoolline.cpp
  src/libs/vtools/tools/vtoolseamallowance.cpp
  src/libs/vtools/tools/vtoolseamallowance.h
  src/libs/vwidgets/linetype_combobox.cpp
  src/libs/vwidgets/linetype_combobox.h
  src/libs/vwidgets/lineweight_combobox.cpp
  src/libs/vwidgets/lineweight_combobox.h
  src/libs/vwidgets/vsimplecurve.cpp
  src/libs/vwidgets/vwidgets.pri
  src/test/Seamly2DTest/tst_vlayoutdetail.cpp
Labels: Detail mode, UI, preferences, New Detail features, New Layout feature

#502 Revert to weekly build schedule
  .github/workflows/build-weekly-release.yml
Labels: build

#512 Update README.md
  .github/README.md
Labels: repository
