Repository FashionFreedom/Seamly2D, pull requests merged in 2022-11, with the labels that each got.

#700 Fix: Issue 699 - Fix compiler warnings
  src/app/seamly2d/dialogs/calculator_dialog.cpp
  src/app/seamly2d/dialogs/calculator_dialog.h
  src/app/seamly2d/dialogs/shortcuts_dialog.cpp
  src/app/seamly2d/mainwindow.cpp
  src/app/seamlyme/dialogs/me_shortcuts_dialog.cpp
  src/libs/fervor/fvupdater.cpp
  src/libs/vtools/dialogs/tools/dialogtool.h
  src/libs/vtools/dialogs/tools/piece/dialogseamallowance.cpp
  src/libs/vtools/tools/drawTools/operation/vabstractoperation.h
  src/libs/vtools/visualization/line/operation/vistoolmove.cpp
  src/libs/vwidgets/calculator/button.h
  src/libs/vwidgets/calculator/calculator.cpp
  src/libs/vwidgets/color_combobox.h
  src/libs/vwidgets/vgrainlineitem.h
  src/libs/vwidgets/vgraphicssimpletextitem.cpp
  src/libs/vwidgets/vmaingraphicsview.cpp
  src/libs/vwidgets/vmaingraphicsview.h
  src/test/Seamly2DTest/tst_vposter.cpp
Labels: build

#698 Feat: Improve the Intersection XY Point tool
  src/app/seamly2d/core/vtooloptionspropertybrowser.cpp
  src/app/seamly2d/mainwindow.cpp
  src/app/seamly2d/mainwindow.h
  src/app/seamly2d/mainwindow.ui
  src/app/seamly2d/share/resources/toolicon.qrc
  src/app/seamly2d/share/resources/toolicon/32x32/point_intersectxy_icon.png
  src/app/seamly2d/share/resources/toolicon/32x32/point_intersectxy_icon@2x.png
  src/app/seamly2d/xml/vpattern.cpp
  src/app/seamly2d/xml/vpattern.h
  src/libs/ifc/ifcdef.cpp
  src/libs/ifc/ifcdef.h
  src/libs/ifc/schema.qrc
  src/libs/ifc/schema/pattern/v0.6.4.xsd
  src/libs/ifc/xml/vpatternconverter.cpp
  src/libs/ifc/xml/vpatternconverter.h
  src/libs/vtools/dialogs/dialogs.pri
  src/libs/vtools/dialogs/tooldialogs.h
  src/libs/vtools/dialogs/tools/dialogpointofintersection.cpp
  src/libs/vtools/dialogs/tools/dialogpointofintersection.h
  src/libs/vtools/dialogs/tools/dialogpointofintersection.ui
  src/libs/vtools/dialogs/tools/dialogtool.cpp
  src/libs/vtools/dialogs/tools/point_intersectxy_dialog.cpp
  src/libs/vtools/dialogs/tools/point_intersectxy_dialog.h
  src/libs/vtools/dialogs/tools/point_intersectxy_dialog.ui
  src/libs/vtools/tools/drawTools/drawtools.h
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/point_intersectxy_tool.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/point_intersectxy_tool.h
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toollinepoint/doubleline_point_tool.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toollinepoint/doubleline_point_tool.h
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/vtoolpointofintersection.h
  src/libs/vtools/tools/drawTools/vdrawtool.cpp
  src/libs/vtools/tools/drawTools/vdrawtool.h
  src/libs/vtools/tools/tools.pri
  src/libs/vtools/visualization/line/point_intersectxy_visual.cpp
  src/libs/vtools/visualization/line/point_intersectxy_visual.h
  src/libs/vtools/visualization/line/visline.cpp
  src/libs/vtools/visualization/line/visline.h
  src/libs/vtools/visualization/line/vistoolpointofintersection.h
  src/libs/vtools/visualization/path/vispath.cpp
  src/libs/vtools/visualization/path/vispath.h
  src/libs/vtools/visualization/visualization.cpp
  src/libs/vtools/visualization/visualization.h
  src/libs/vtools/visualization/visualization.pri
  src/libs/vwidgets/lineweight_combobox.cpp
Labels: Draft mode, New Draw features, visualization, Point tools

#715 linux: use PREFIX instead of hardcoded /usr during install
  src/app/seamly2d/seamly2d.pro
  src/app/seamlyme/seamlyme.pro
Labels: build, flatpak

#725 feat: improve export dialog
  src/app/seamly2d/core/vcmdexport.cpp
  src/app/seamly2d/core/vcmdexport.h
  src/app/seamly2d/dialogs/configpages/preferencesconfigurationpage.cpp
  src/app/seamly2d/dialogs/configpages/preferencesconfigurationpage.ui
  src/app/seamly2d/dialogs/configpages/preferencesgraphicsviewpage.cpp
  src/app/seamly2d/dialogs/configpages/preferencesgraphicsviewpage.ui
  src/app/seamly2d/dialogs/configpages/preferencespathpage.cpp
  src/app/seamly2d/dialogs/dialoglayoutsettings.cpp
  src/app/seamly2d/dialogs/dialoglayoutsettings.h
  src/app/seamly2d/dialogs/dialoglayoutsettings.ui
  src/app/seamly2d/dialogs/dialogs.pri
  src/app/seamly2d/dialogs/dialogsavelayout.h
  src/app/seamly2d/dialogs/dialogsavelayout.ui
  src/app/seamly2d/dialogs/export_layout_dialog.cpp
  src/app/seamly2d/dialogs/export_layout_dialog.h
  src/app/seamly2d/dialogs/export_layout_dialog.ui
  src/app/seamly2d/dialogs/vabstractlayoutdialog.cpp
  src/app/seamly2d/dialogs/vabstractlayoutdialog.h
  src/app/seamly2d/mainwindow.cpp
  src/app/seamly2d/mainwindowsnogui.cpp
  src/app/seamly2d/mainwindowsnogui.h
  src/libs/vmisc/vcommonsettings.cpp
  src/libs/vmisc/vcommonsettings.h
  src/libs/vmisc/vsettings.cpp
  src/libs/vmisc/vsettings.h
Labels: enhancement, Piece mode, Draft mode, Layout mode, export

#728 Issue 340 show angle tooltip
  src/libs/vmisc/share/resources/icon.qrc
  src/libs/vmisc/share/resources/icon/64x64/rotation..png
  src/libs/vtools/dialogs/tools/dialogarc.ui
  src/libs/vtools/dialogs/tools/dialogarcwithlength.ui
  src/libs/vtools/dialogs/tools/dialogcurveintersectaxis.ui
  src/libs/vtools/dialogs/tools/dialogellipticalarc.ui
  src/libs/vtools/dialogs/tools/dialogendline.ui
  src/libs/vtools/dialogs/tools/dialoglineintersectaxis.ui
  src/libs/vtools/dialogs/tools/dialogmove.ui
  src/libs/vtools/dialogs/tools/dialogrotation.ui
Labels: enhancement, Draft mode, UI

#732 Feature: issue #291 - add new measurement
  src/app/seamlyme/share/resources/diagrams/Jp6.svg
  src/app/share/tables/templates/template_all_measurements.vit
  src/libs/vpatterndb/measurements.cpp
  src/libs/vpatterndb/measurements.h
  src/libs/vpatterndb/vtranslatemeasurements.cpp
  src/test/Seamly2DTest/tst_nameregexp.cpp
Labels: measurements, New measurements feature, images, New SeamlyMe features

#733 ci: enable parallel builds for mac as github hosted mac runners have 3 CPUs
  .github/workflows/build-auto-prerelease-on-merge.yml
  .github/workflows/build-auto-release-on-cron.yml
  .github/workflows/build-manual-prerelease-macos.yml
  .github/workflows/build-manual-release-all.yml
Labels: Mac

#737 bug: Issue 736 fix intersectxy dialog
  src/libs/vtools/dialogs/tools/point_intersectxy_dialog.ui
Labels: bug, Draft mode, UI

#739 Issue 738 enhance insert node tool
  src/app/seamly2d/dialogs/dialoghistory.cpp
  src/app/seamly2d/mainwindow.cpp
  src/app/seamly2d/mainwindow.h
  src/app/seamly2d/mainwindow.ui
  src/app/seamly2d/share/resources/cursor.qrc
  src/app/seamly2d/share/resources/cursor/insert_node_cursor.png
  src/app/seamly2d/share/resources/cursor/insert_node_cursor@2x.png
  src/app/seamly2d/share/resources/cursor/insert_nodes_cursor.png
  src/app/seamly2d/share/resources/cursor/insert_nodes_cursor@2x.png
  src/app/seamly2d/share/resources/toolicon.qrc
  src/app/seamly2d/share/resources/toolicon/32x32/insert_node.png
  src/app/seamly2d/share/resources/toolicon/32x32/insert_node@2x.png
  src/app/seamly2d/share/resources/toolicon/32x32/insert_nodes_icon.png
  src/app/seamly2d/share/resources/toolicon/32x32/insert_nodes_icon@2x.png
  src/app/seamly2d/share/resources/toolicon/svg/insert_node.svg
  src/app/seamly2d/share/resources/toolicon/svg/insert_nodes_icon.svg
  src/app/seamly2d/xml/vpattern.cpp
  src/libs/vgeometry/vabstractcubicbezierpath.cpp
  src/libs/vgeometry/vabstractcubicbezierpath.h
  src/libs/vgeometry/vabstractcurve.cpp
  src/libs/vgeometry/vabstractcurve.h
  src/libs/vgeometry/varc.cpp
  src/libs/vgeometry/varc.h
  src/libs/vgeometry/vcubicbezier.cpp
  src/libs/vgeometry/vcubicbezier.h
  src/libs/vgeometry/vellipticalarc.cpp
  src/libs/vgeometry/vellipticalarc.h
  src/libs/vgeometry/vspline.cpp
  src/libs/vgeometry/vspline.h
  src/libs/vmisc/def.h
  src/libs/vmisc/share/resources/icon.qrc
  src/libs/vmisc/share/resources/icon/24x24/reverse.png
  src/libs/vpatterndb/vpiecepath.cpp
  src/libs/vtools/dialogs/dialogs.pri
  src/libs/vtools/dialogs/tooldialogs.h
  src/libs/vtools/dialogs/tools/dialoginsertnode.cpp
  src/libs/vtools/dialogs/tools/dialoginsertnode.ui
  src/libs/vtools/dialogs/tools/dialogtool.cpp
  src/libs/vtools/dialogs/tools/dialogtool.h
  src/libs/vtools/dialogs/tools/insert_nodes_dialog.cpp
  src/libs/vtools/dialogs/tools/insert_nodes_dialog.h
  src/libs/vtools/dialogs/tools/insert_nodes_dialog.ui
  src/libs/vtools/dialogs/tools/piece/dialoginternalpath.cpp
  src/libs/vtools/dialogs/tools/piece/dialogseamallowance.cpp
  src/libs/vtools/tools/drawTools/operation/vtoolmove.cpp
  src/libs/vtools/tools/drawTools/toolcurve/vabstractspline.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/vtoolpointofintersectioncurves.cpp
  src/libs/vtools/tools/vtoolseamallowance.cpp
  src/libs/vtools/tools/vtoolseamallowance.h
  src/libs/vtools/visualization/line/operation/vistoolmove.cpp
  src/libs/vtools/visualization/path/vistoolpointofintersectioncurves.cpp
  src/libs/vwidgets/vsimplecurve.cpp
  src/test/Seamly2DTest/tst_vabstractcurve.cpp
  src/test/Seamly2DTest/tst_vabstractcurve.h
  src/test/Seamly2DTest/tst_varc.cpp
  src/test/Seamly2DTest/tst_vellipticalarc.cpp
  src/test/Seamly2DTest/tst_vspline.cpp
Labels: enhancement, Draft mode, UI
