Repository FashionFreedom/Seamly2D, pull requests merged in 2023-01, with the labels that each got.

#761 Fix: Issue 758 calculating formula crashes
  src/libs/qmuparser/qmuparserbase.cpp
Labels: bug, Draft mode, formulas

#796 Fix: Default notch settings not recognized in tool dialogs
  src/libs/ifc/xml/vabstractpattern.cpp
Labels: bug, Draft mode

#825 Refactor: Seam allowance to cut line
  share/translations/seamly2d.ts
  share/translations/seamly2d_cs_CZ.ts
  share/translations/seamly2d_de_DE.ts
  share/translations/seamly2d_el_GR.ts
  share/translations/seamly2d_en_CA.ts
  share/translations/seamly2d_en_IN.ts
  share/translations/seamly2d_en_US.ts
  share/translations/seamly2d_es_ES.ts
  share/translations/seamly2d_fi_FI.ts
  share/translations/seamly2d_fr_FR.ts
  share/translations/seamly2d_he_IL.ts
  share/translations/seamly2d_id_ID.ts
  share/translations/seamly2d_it_IT.ts
  share/translations/seamly2d_nl_NL.ts
  share/translations/seamly2d_pt_BR.ts
  share/translations/seamly2d_ro_RO.ts
  share/translations/seamly2d_ru_RU.ts
  share/translations/seamly2d_uk_UA.ts
  share/translations/seamly2d_zh_CN.ts
  src/app/seamly2d/dialogs/configpages/preferencespatternpage.ui
  src/libs/vtools/dialogs/tools/piece/pattern_piece_dialog.ui
Labels: Piece mode, refactor, UI

#830 Fixed pattern piece label resize issue when label is rotated (issue #829)
  src/libs/vwidgets/vtextgraphicsitem.cpp
Labels: bug, Piece mode, UI, labels

#841 fix typos in filename rotation.png
  share/translations/seamly2d.ts
  share/translations/seamly2d_cs_CZ.ts
  share/translations/seamly2d_de_DE.ts
  share/translations/seamly2d_el_GR.ts
  share/translations/seamly2d_en_CA.ts
  share/translations/seamly2d_en_IN.ts
  share/translations/seamly2d_en_US.ts
  share/translations/seamly2d_es_ES.ts
  share/translations/seamly2d_fi_FI.ts
  share/translations/seamly2d_fr_FR.ts
  share/translations/seamly2d_he_IL.ts
  share/translations/seamly2d_id_ID.ts
  share/translations/seamly2d_it_IT.ts
  share/translations/seamly2d_nl_NL.ts
  share/translations/seamly2d_pt_BR.ts
  share/translations/seamly2d_ro_RO.ts
  share/translations/seamly2d_ru_RU.ts
  share/translations/seamly2d_uk_UA.ts
  share/translations/seamly2d_zh_CN.ts
  src/libs/vmisc/share/resources/icon.qrc
  src/libs/vmisc/share/resources/icon/64x64/rotation.png
  src/libs/vtools/dialogs/tools/dialogarc.ui
  src/libs/vtools/dialogs/tools/dialogarcwithlength.ui
  src/libs/vtools/dialogs/tools/dialogcurveintersectaxis.ui
  src/libs/vtools/dialogs/tools/dialogellipticalarc.ui
  src/libs/vtools/dialogs/tools/dialogendline.ui
  src/libs/vtools/dialogs/tools/dialoglineintersectaxis.ui
  src/libs/vtools/dialogs/tools/dialogmove.ui
  src/libs/vtools/dialogs/tools/dialogrotation.ui
Labels: bug

#847 BUG: fix zero width seam allowance in pattern piece tool
  share/translations/seamly2d.ts
  share/translations/seamly2d_cs_CZ.ts
  share/translations/seamly2d_de_DE.ts
  share/translations/seamly2d_el_GR.ts
  share/translations/seamly2d_en_CA.ts
  share/translations/seamly2d_en_IN.ts
  share/translations/seamly2d_en_US.ts
  share/translations/seamly2d_es_ES.ts
  share/translations/seamly2d_fi_FI.ts
  share/translations/seamly2d_fr_FR.ts
  share/translations/seamly2d_he_IL.ts
  share/translations/seamly2d_id_ID.ts
  share/translations/seamly2d_it_IT.ts
  share/translations/seamly2d_nl_NL.ts
  share/translations/seamly2d_pt_BR.ts
  share/translations/seamly2d_ro_RO.ts
  share/translations/seamly2d_ru_RU.ts
  share/translations/seamly2d_uk_UA.ts
  share/translations/seamly2d_zh_CN.ts
  src/app/seamly2d/dialogs/configpages/preferencespatternpage.ui
  src/app/seamly2d/dialogs/pieces_widget.cpp
  src/app/seamly2d/dialogs/vwidgetgroups.cpp
  src/app/seamly2d/mainwindow.cpp
  src/libs/vtools/dialogs/tools/piece/pattern_piece_dialog.ui
  src/libs/vtools/tools/pattern_piece_tool.cpp
  src/libs/vtools/tools/pattern_piece_tool.h
  src/libs/vwidgets/nonscalingfill_pathitem.cpp
  src/libs/vwidgets/nonscalingfill_pathitem.h
  src/libs/vwidgets/vgrainlineitem.cpp
  src/libs/vwidgets/vwidgets.pri
Labels: bug, Piece mode
