Repository FashionFreedom/Seamly2D, pull requests merged in 2024-08, with the labels that each got.

#1161 flathub: add linux screenshot
  dist/seamly2d_screenshot_linux.png
Labels: Linux

#1168 feat: user can import jpeg as background images
  src/app/seamly2d/mainwindow.cpp
Labels: enhancement, Draft mode, images

#1180 feat: increase tooltip font size
  src/libs/vtools/tools/drawTools/operation/vabstractoperation.cpp
  src/libs/vtools/tools/drawTools/toolcurve/vabstractspline.cpp
  src/libs/vtools/tools/drawTools/toolcurve/vtoolarc.cpp
  src/libs/vtools/tools/drawTools/toolcurve/vtoolarcwithlength.cpp
  src/libs/vtools/tools/drawTools/toolcurve/vtoolellipticalarc.cpp
  src/libs/vtools/tools/drawTools/toolpoint/tooldoublepoint/vtooldoublepoint.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toolcut/vtoolcutarc.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toolcut/vtoolcutspline.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toolcut/vtoolcutsplinepath.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toollinepoint/doubleline_point_tool.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toollinepoint/vtoolalongline.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toollinepoint/vtoolheight.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toollinepoint/vtoollineintersectaxis.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toollinepoint/vtoollinepoint.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toollinepoint/vtoolshoulderpoint.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/vtoolbasepoint.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/vtoollineintersect.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/vtoolpointofcontact.cpp
  src/libs/vtools/tools/drawTools/vtoolline.cpp
Labels: Draft mode, UI

#1181 bug: limit fx dialog tabs by parent dialog
  src/app/seamly2d/core/vformulapropertyeditor.cpp
  src/app/seamly2d/dialogs/dialogvariables.cpp
  src/app/seamlyme/tmainwindow.cpp
  src/libs/vmisc/def.h
  src/libs/vtools/dialogs/support/edit_formula_dialog.cpp
  src/libs/vtools/dialogs/support/edit_formula_dialog.h
  src/libs/vtools/dialogs/tools/dialogalongline.cpp
  src/libs/vtools/dialogs/tools/dialogarc.cpp
  src/libs/vtools/dialogs/tools/dialogarcwithlength.cpp
  src/libs/vtools/dialogs/tools/dialogbisector.cpp
  src/libs/vtools/dialogs/tools/dialogcurveintersectaxis.cpp
  src/libs/vtools/dialogs/tools/dialogcutarc.cpp
  src/libs/vtools/dialogs/tools/dialogcutspline.cpp
  src/libs/vtools/dialogs/tools/dialogcutsplinepath.cpp
  src/libs/vtools/dialogs/tools/dialogellipticalarc.cpp
  src/libs/vtools/dialogs/tools/dialogendline.cpp
  src/libs/vtools/dialogs/tools/dialoglineintersectaxis.cpp
  src/libs/vtools/dialogs/tools/dialogmove.cpp
  src/libs/vtools/dialogs/tools/dialognormal.cpp
  src/libs/vtools/dialogs/tools/dialogpointofcontact.cpp
  src/libs/vtools/dialogs/tools/dialogrotation.cpp
  src/libs/vtools/dialogs/tools/dialogshoulderpoint.cpp
  src/libs/vtools/dialogs/tools/dialogspline.cpp
  src/libs/vtools/dialogs/tools/dialogsplinepath.cpp
  src/libs/vtools/dialogs/tools/intersect_circles_dialog.cpp
  src/libs/vtools/dialogs/tools/intersect_circletangent_dialog.cpp
  src/libs/vtools/dialogs/tools/piece/dialoginternalpath.cpp
  src/libs/vtools/dialogs/tools/piece/pattern_piece_dialog.cpp
  src/libs/vtools/tools/vabstracttool.cpp
Labels: bug, Draft mode, UI, variables, SeamlyMe

#1183 bug: Fix linetype combobox in prop editor
  src/app/seamly2d/core/vtooloptionspropertybrowser.cpp
  src/libs/ifc/ifcdef.cpp
  src/libs/ifc/ifcdef.h
  src/libs/vtools/dialogs/tools/dialogalongline.cpp
  src/libs/vtools/dialogs/tools/dialogarc.cpp
  src/libs/vtools/dialogs/tools/dialogbisector.cpp
  src/libs/vtools/dialogs/tools/dialogcutarc.cpp
  src/libs/vtools/dialogs/tools/dialogcutspline.cpp
  src/libs/vtools/dialogs/tools/dialogcutsplinepath.cpp
  src/libs/vtools/dialogs/tools/dialogellipticalarc.cpp
  src/libs/vtools/dialogs/tools/dialogendline.cpp
  src/libs/vtools/dialogs/tools/dialogheight.cpp
  src/libs/vtools/dialogs/tools/dialogline.cpp
  src/libs/vtools/dialogs/tools/dialoglineintersect.cpp
  src/libs/vtools/dialogs/tools/dialognormal.cpp
  src/libs/vtools/dialogs/tools/dialogpointofcontact.cpp
  src/libs/vtools/dialogs/tools/dialogshoulderpoint.cpp
  src/libs/vtools/dialogs/tools/dialogspline.cpp
  src/libs/vtools/dialogs/tools/dialogsplinepath.cpp
  src/libs/vtools/dialogs/tools/dialogtriangle.cpp
  src/libs/vtools/dialogs/tools/point_intersectxy_dialog.cpp
  src/libs/vtools/dialogs/tools/union_dialog.cpp
  src/libs/vtools/tools/drawTools/operation/vabstractoperation.cpp
  src/libs/vtools/tools/drawTools/toolpoint/tooldoublepoint/vtooldoublepoint.cpp
  src/libs/vwidgets/vmaingraphicsscene.h
  src/libs/vwidgets/vsimplecurve.cpp
  src/libs/vwidgets/vsimplecurve.h
  src/libs/vwidgets/vsimplepoint.cpp
  src/libs/vwidgets/vsimplepoint.h
Labels: bug, Draft mode, UI

#1182 bug: Fix zoom shortcuts
  share/translations/seamly2d_cs_CZ.ts
  share/translations/seamly2d_de_DE.ts
  share/translations/seamly2d_el_GR.ts
  share/translations/seamly2d_en_CA.ts
  share/translations/seamly2d_en_GB.ts
  share/translations/seamly2d_en_IN.ts
  share/translations/seamly2d_en_US.ts
  share/translations/seamly2d_es_ES.ts
  share/translations/seamly2d_fi_FI.ts
  share/translations/seamly2d_fr_FR.ts
  share/translations/seamly2d_he_IL.ts
  share/translations/seamly2d_id_ID.ts
  share/translations/seamly2d_it_IT.ts
  share/translations/seamly2d_nl_NL.ts
  share/translations/seamly2d_pt_BR.ts
  share/translations/seamly2d_ro_RO.ts
  share/translations/seamly2d_ru_RU.ts
  share/translations/seamly2d_uk_UA.ts
  share/translations/seamly2d_zh_CN.ts
  src/app/seamly2d/dialogs/shortcuts_dialog.cpp
  src/app/seamly2d/mainwindow.cpp
  src/app/seamly2d/mainwindow.ui
Labels: bug, UI
