Repository FashionFreedom/Seamly2D, pull requests merged in 2024-11, with the labels that each got.

#1208 bug: fix position option in edit fx dialog
  src/libs/vtools/dialogs/support/edit_formula_dialog.cpp
  src/libs/vtools/dialogs/support/edit_formula_dialog.h
  src/libs/vtools/dialogs/support/editlabeltemplate_dialog.cpp
  src/libs/vtools/dialogs/support/editlabeltemplate_dialog.h
Labels: bug, Draft mode

#1211 bug: eliminate compiler warnings
  src/app/seamly2d/dialogs/pieces_widget.cpp
  src/app/seamly2d/dialogs/welcome_dialog.cpp
  src/app/seamly2d/dialogs/welcome_dialog.h
  src/app/seamly2d/mainwindow.h
  src/app/seamlyme/dialogs/me_welcome_dialog.cpp
  src/app/seamlyme/dialogs/me_welcome_dialog.h
  src/libs/tools/tools.pro
  src/libs/vmisc/share/resources/icon.qrc
  src/libs/vtools/tools/pattern_piece_tool.cpp
Labels: bug, minor, build

#1209 bug: fix draggable menu items in pattern pieces & pref dialogs
  src/app/seamly2d/dialogs/dialogpreferences.ui
  src/libs/vtools/dialogs/tools/piece/pattern_piece_dialog.ui
Labels: bug, Piece mode, Draft mode, UI

#1220 bug: Remove minimum point name font size when zooming
  src/libs/vwidgets/vscenepoint.cpp
Labels: bug, Operations Tools

#1214 bug: fix xml tag order
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/vtoolbasepoint.cpp
Labels: bug, file format, Seamly2D

#1221 fix: bounding boxes of exported svg pattern pieces are now correct
  src/libs/vformat/svg_generator.cpp
  src/libs/vformat/svg_generator.h
Labels: Piece mode, export

#1225 fix: fx dialog positioning
  src/libs/vtools/dialogs/support/edit_formula_dialog.cpp
  src/libs/vtools/dialogs/support/edit_formula_dialog.ui
Labels: bug, Draft mode, UI, fixed, formulas
