Repository FashionFreedom/Seamly2D, pull requests merged in 2024-07, with the labels that each got.

#1130 maintenance: correct comments for vcontainer
  src/libs/vpatterndb/vcontainer.cpp
Labels: Maintenance

#1137 bug: fix file errors when running collection
  src/libs/ifc/xml/abstract_converter.cpp
Labels: bug, test suite related, major, CI

#1129 Fix: high CPU usage with spline control points
  src/app/seamly2d/mainwindow.cpp
  src/libs/vtools/tools/drawTools/toolcurve/vabstractspline.cpp
  src/libs/vtools/tools/drawTools/toolcurve/vabstractspline.h
  src/libs/vtools/tools/drawTools/toolcurve/vtoolarc.cpp
  src/libs/vtools/tools/drawTools/toolcurve/vtoolarcwithlength.cpp
  src/libs/vtools/tools/drawTools/toolcurve/vtoolcubicbezier.cpp
  src/libs/vtools/tools/drawTools/toolcurve/vtoolcubicbezier.h
  src/libs/vtools/tools/drawTools/toolcurve/vtoolcubicbezierpath.cpp
  src/libs/vtools/tools/drawTools/toolcurve/vtoolcubicbezierpath.h
  src/libs/vtools/tools/drawTools/toolcurve/vtoolellipticalarc.cpp
  src/libs/vtools/tools/drawTools/toolcurve/vtoolspline.cpp
  src/libs/vtools/tools/drawTools/toolcurve/vtoolspline.h
  src/libs/vtools/tools/drawTools/toolcurve/vtoolsplinepath.cpp
  src/libs/vtools/tools/drawTools/toolcurve/vtoolsplinepath.h
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toolcut/vtoolcut.h
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toollinepoint/doubleline_point_tool.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toollinepoint/vtoollinepoint.cpp
  src/libs/vtools/tools/pattern_piece_tool.cpp
  src/libs/vtools/visualization/line/intersect_circles_visual.cpp
  src/libs/vtools/visualization/line/intersect_circletangent_visual.cpp
  src/libs/vtools/visualization/line/vistoolpointofcontact.cpp
  src/libs/vtools/visualization/visualization.cpp
  src/libs/vwidgets/global.cpp
  src/libs/vwidgets/global.h
  src/libs/vwidgets/scalesceneitems.cpp
  src/libs/vwidgets/scalesceneitems.h
  src/libs/vwidgets/scene_rect.cpp
  src/libs/vwidgets/scene_rect.h
  src/libs/vwidgets/vcontrolpointspline.cpp
  src/libs/vwidgets/vcontrolpointspline.h
  src/libs/vwidgets/vcurvepathitem.cpp
  src/libs/vwidgets/vcurvepathitem.h
  src/libs/vwidgets/vscenepoint.cpp
Labels: bug, Draft mode, UI, performance

#1134 feature: use current pen preference
  src/app/seamly2d/dialogs/configpages/preferencesgraphicsviewpage.cpp
  src/app/seamly2d/dialogs/configpages/preferencesgraphicsviewpage.ui
  src/libs/vmisc/vcommonsettings.cpp
  src/libs/vmisc/vcommonsettings.h
  src/libs/vtools/dialogs/tools/dialogalongline.cpp
  src/libs/vtools/dialogs/tools/dialogbisector.cpp
  src/libs/vtools/dialogs/tools/dialogheight.cpp
  src/libs/vtools/dialogs/tools/dialognormal.cpp
  src/libs/vtools/dialogs/tools/dialogshoulderpoint.cpp
  src/libs/vtools/dialogs/tools/point_intersectxy_dialog.cpp
Labels: enhancement, preferences, New UI feature

#1142 maintenance: update seamly2d about dialog
  src/app/seamly2d/dialogs/about2d_dialog.ui
Labels: About, Maintenance

#1143 feat: Add end point option to point on arcs, curves, and splines
  share/translations/seamly2d_cs_CZ.ts
  share/translations/seamly2d_de_DE.ts
  share/translations/seamly2d_el_GR.ts
  share/translations/seamly2d_en_CA.ts
  share/translations/seamly2d_en_GB.ts
  share/translations/seamly2d_en_IN.ts
  share/translations/seamly2d_en_US.ts
  share/translations/seamly2d_es_ES.ts
  share/translations/seamly2d_fi_FI.ts
  share/translations/seamly2d_fr_FR.ts
  share/translations/seamly2d_he_IL.ts
  share/translations/seamly2d_id_ID.ts
  share/translations/seamly2d_it_IT.ts
  share/translations/seamly2d_nl_NL.ts
  share/translations/seamly2d_pt_BR.ts
  share/translations/seamly2d_ro_RO.ts
  share/translations/seamly2d_ru_RU.ts
  share/translations/seamly2d_uk_UA.ts
  share/translations/seamly2d_zh_CN.ts
  src/app/seamly2d/core/vtooloptionspropertybrowser.cpp
  src/app/seamly2d/core/vtooloptionspropertybrowser.h
  src/app/seamly2d/xml/vpattern.cpp
  src/libs/ifc/ifcdef.cpp
  src/libs/ifc/ifcdef.h
  src/libs/ifc/schema.qrc
  src/libs/ifc/schema/pattern/v0.7.0.xsd
  src/libs/ifc/xml/vpatternconverter.cpp
  src/libs/ifc/xml/vpatternconverter.h
  src/libs/vgeometry/vspline.cpp
  src/libs/vmisc/def.cpp
  src/libs/vmisc/def.h
  src/libs/vpropertyexplorer/plugins/direction_property.cpp
  src/libs/vpropertyexplorer/plugins/direction_property.h
  src/libs/vpropertyexplorer/vproperties.h
  src/libs/vpropertyexplorer/vpropertyexplorer.pri
  src/libs/vtools/dialogs/tools/dialogcutarc.cpp
  src/libs/vtools/dialogs/tools/dialogcutarc.h
  src/libs/vtools/dialogs/tools/dialogcutarc.ui
  src/libs/vtools/dialogs/tools/dialogcutspline.cpp
  src/libs/vtools/dialogs/tools/dialogcutspline.h
  src/libs/vtools/dialogs/tools/dialogcutspline.ui
  src/libs/vtools/dialogs/tools/dialogcutsplinepath.cpp
  src/libs/vtools/dialogs/tools/dialogcutsplinepath.h
  src/libs/vtools/dialogs/tools/dialogcutsplinepath.ui
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toolcut/vtoolcut.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toolcut/vtoolcut.h
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toolcut/vtoolcutarc.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toolcut/vtoolcutarc.h
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toolcut/vtoolcutspline.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toolcut/vtoolcutspline.h
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toolcut/vtoolcutsplinepath.cpp
  src/libs/vtools/tools/drawTools/toolpoint/toolsinglepoint/toolcut/vtoolcutsplinepath.h
  src/libs/vtools/visualization/path/vistoolcutarc.cpp
  src/libs/vtools/visualization/path/vistoolcutarc.h
  src/libs/vtools/visualization/path/vistoolcutspline.cpp
  src/libs/vtools/visualization/path/vistoolcutspline.h
  src/libs/vtools/visualization/path/vistoolcutsplinepath.cpp
  src/libs/vtools/visualization/path/vistoolcutsplinepath.h
Labels: Draft mode, New Draft features

#1155 No more warning popup when using a math function with a semicolon
  src/libs/qmuparser/qmuparsertokenreader.cpp
Labels: bug, formulas

#1157 fix: no more error popup when cancelling image import
  src/app/seamly2d/mainwindow.cpp
Labels: bug, Draft mode, images

#1156 Auto scroll when moving pattern piece is now independent from the piece's size
  src/libs/vtools/tools/pattern_piece_tool.cpp
Labels: bug, Piece mode
