Repository FashionFreedom/Seamly2D, pull requests merged in 2024-03, with the labels that each got.

#1066 fix: export layout dialog
  src/app/seamly2d/dialogs/export_layout_dialog.ui
Labels: bug, Draft mode, UI

#1071 ci: bump softprops/action-gh-release to address node16 deprecations
  .github/workflows/ci.yml
Labels: Maintenance

#1074 bug: fix and widen tool dialogs
  src/app/seamly2d/dialogs/configpages/preferencesgraphicsviewpage.ui
  src/libs/vtools/dialogs/tools/dialogalongline.ui
  src/libs/vtools/dialogs/tools/dialogarc.ui
  src/libs/vtools/dialogs/tools/dialogarcwithlength.ui
  src/libs/vtools/dialogs/tools/dialogbisector.ui
  src/libs/vtools/dialogs/tools/dialogcubicbezier.ui
  src/libs/vtools/dialogs/tools/dialogcubicbezierpath.ui
  src/libs/vtools/dialogs/tools/dialogcurveintersectaxis.ui
  src/libs/vtools/dialogs/tools/dialogcutarc.ui
  src/libs/vtools/dialogs/tools/dialogcutspline.ui
  src/libs/vtools/dialogs/tools/dialogcutsplinepath.ui
  src/libs/vtools/dialogs/tools/dialogellipticalarc.ui
  src/libs/vtools/dialogs/tools/dialogendline.ui
  src/libs/vtools/dialogs/tools/dialogheight.ui
  src/libs/vtools/dialogs/tools/dialogline.ui
  src/libs/vtools/dialogs/tools/dialoglineintersect.ui
  src/libs/vtools/dialogs/tools/dialoglineintersectaxis.ui
  src/libs/vtools/dialogs/tools/dialogmirrorbyaxis.ui
  src/libs/vtools/dialogs/tools/dialogmirrorbyline.ui
  src/libs/vtools/dialogs/tools/dialogmove.ui
  src/libs/vtools/dialogs/tools/dialognormal.ui
  src/libs/vtools/dialogs/tools/dialogpointfromarcandtangent.ui
  src/libs/vtools/dialogs/tools/dialogpointofcontact.ui
  src/libs/vtools/dialogs/tools/dialogpointofintersectionarcs.ui
  src/libs/vtools/dialogs/tools/dialogpointofintersectioncurves.ui
  src/libs/vtools/dialogs/tools/dialogrotation.ui
  src/libs/vtools/dialogs/tools/dialogshoulderpoint.ui
  src/libs/vtools/dialogs/tools/dialogsinglepoint.ui
  src/libs/vtools/dialogs/tools/dialogspline.ui
  src/libs/vtools/dialogs/tools/dialogsplinepath.ui
  src/libs/vtools/dialogs/tools/dialogtriangle.ui
  src/libs/vtools/dialogs/tools/dialogtruedarts.ui
  src/libs/vtools/dialogs/tools/editgroup_dialog.ui
  src/libs/vtools/dialogs/tools/insert_nodes_dialog.ui
  src/libs/vtools/dialogs/tools/intersect_circles_dialog.ui
  src/libs/vtools/dialogs/tools/intersect_circletangent_dialog.ui
  src/libs/vtools/dialogs/tools/point_intersectxy_dialog.ui
  src/libs/vtools/dialogs/tools/union_dialog.ui
Labels: bug, translations, UI

#1072 maintenance: add locations to lupdate
  Seamly2D.pro
  share/translations/seamly2d_cs_CZ.ts
  share/translations/seamly2d_de_DE.ts
  share/translations/seamly2d_el_GR.ts
  share/translations/seamly2d_en_CA.ts
  share/translations/seamly2d_en_GB.ts
  share/translations/seamly2d_en_IN.ts
  share/translations/seamly2d_en_US.ts
  share/translations/seamly2d_es_ES.ts
  share/translations/seamly2d_fi_FI.ts
  share/translations/seamly2d_fr_FR.ts
  share/translations/seamly2d_he_IL.ts
  share/translations/seamly2d_id_ID.ts
  share/translations/seamly2d_it_IT.ts
  share/translations/seamly2d_nl_NL.ts
  share/translations/seamly2d_pt_BR.ts
  share/translations/seamly2d_ro_RO.ts
  share/translations/seamly2d_ru_RU.ts
  share/translations/seamly2d_uk_UA.ts
  share/translations/seamly2d_zh_CN.ts
Labels: Maintenance

#1080 feat: improve intersect arc line icon and cursor
  src/app/seamly2d/dialogs/groups_widget.cpp
  src/app/seamly2d/dialogs/history_dialog.cpp
  src/app/seamly2d/mainwindow.cpp
  src/app/seamly2d/mainwindow.ui
  src/app/seamly2d/share/resources/cursor.qrc
  src/app/seamly2d/share/resources/cursor/point_intersect_arc_line_cursor.png
  src/app/seamly2d/share/resources/cursor/point_intersect_arc_line_cursor@2x.png
  src/app/seamly2d/share/resources/cursor/pointcontact_cursor.png
  src/app/seamly2d/share/resources/cursor/pointcontact_cursor@2x.png
  src/app/seamly2d/share/resources/cursor/svg/point_intersect_arc_line_cursor.svg
  src/app/seamly2d/share/resources/toolicon.qrc
  src/app/seamly2d/share/resources/toolicon/32x32/point_intersect_arc_line.png
  src/app/seamly2d/share/resources/toolicon/32x32/point_intersect_arc_line@2x.png
  src/app/seamly2d/share/resources/toolicon/32x32/point_of_contact.png
  src/app/seamly2d/share/resources/toolicon/32x32/point_of_contact@2x.png
  src/app/seamly2d/share/resources/toolicon/svg/point_intersect_arc_line.svg
  src/libs/vtools/dialogs/tools/dialogpointofcontact.cpp
Labels: enhancement, Draft mode, UI

#1082 bug: fix shortcut tooltips
  share/translations/seamly2d_cs_CZ.ts
  share/translations/seamly2d_de_DE.ts
  share/translations/seamly2d_el_GR.ts
  share/translations/seamly2d_en_CA.ts
  share/translations/seamly2d_en_GB.ts
  share/translations/seamly2d_en_IN.ts
  share/translations/seamly2d_en_US.ts
  share/translations/seamly2d_es_ES.ts
  share/translations/seamly2d_fi_FI.ts
  share/translations/seamly2d_fr_FR.ts
  share/translations/seamly2d_he_IL.ts
  share/translations/seamly2d_id_ID.ts
  share/translations/seamly2d_it_IT.ts
  share/translations/seamly2d_nl_NL.ts
  share/translations/seamly2d_pt_BR.ts
  share/translations/seamly2d_ro_RO.ts
  share/translations/seamly2d_ru_RU.ts
  share/translations/seamly2d_uk_UA.ts
  share/translations/seamly2d_zh_CN.ts
  src/app/seamly2d/mainwindow.ui
Labels: bug, Draft mode, UI
